stages:
  - build
  - deploy

build walisonu:
  stage: build
  image: node:11-alpine
  artifacts:
    paths:
      - frontend/build/
  cache:
    paths:
      - frontend/build/
  tags:
    - words
  script:
    - cd frontend
    - npm install
    - npm run build

deploy walisonu:
  stage: deploy
  tags:
    - words
  script:
    - cd frontend
    - rm -rf /home/gitlab-runner/public
    - mkdir /home/gitlab-runner/public
    - mv build /home/gitlab-runner/public
    - rm -rf ../frontend