stages:
  - build
  - deploy

build walisonu:
  stage: build
  image: node:11-alpine
  tags:
    - words
  script:
    - cd frontend
    - sudo npm install
    - sudo npm run build

deploy walisonu:
  stage: deploy
  tags:
    - words
  script:
    - sudo rm -rf /usr/share/nginx/html
    - mkdir /usr/share/nginx/html
    - mv frontend/build /usr/share/nginx/html