stages:
  - build
  - deploya

build walisonu:
  stage: build
  image: node:11-alpine
  tags:
    - words
  script:
    - cd frontend
    - npm install
    - npm run build

deploy walisonu:
  stage: deploy
  tags:
    - words
  script:
    - cd frontend
    - npm start